[versions]
activityComposeVersion = "1.12.2"
appUpdateVersion = "2.1.0"
biometricVersion = "1.2.0-alpha05"
coilComposeVersion = "2.7.0"
converterGsonVersion = "3.0.0"
datastorePreferencesVersion = "1.2.0"
gsonVersion = "2.13.2"
hiltCompilerVersion = "2.57.2"
hiltNavigationComposeVersion = "1.3.0"
kotlin = "2.3.0"
compose = "1.10.0"
kotlinxCoroutinesCore = "1.10.2"
lifecycle = "2.10.0"
loggingInterceptorVersion = "5.3.2"
lottieComposeVersion = "6.7.1"
material3 = "1.4.0"
coreKtx = "1.17.0"
materialIconsExtendedVersion = "1.7.8"
materialVersion = "1.13.0"
playServicesLocationVersion = "21.3.0"
retrofitVersion = "3.0.0"
room = "2.8.4"
hilt = "2.57.2"
appcompat = "1.7.1"
navigationFragmentKtxVersion = "2.9.6"
navigationUiKtxVersion = "2.9.6"
securityCryptoVersion = "1.1.0"
pagingCommonAndroidVersion = "3.3.6"
timberVersion = "5.0.1"
workRuntimeKtxVersion = "2.11.0"
hiltWorkVersion = "1.3.0"
annotationVersion = "1.9.1"
constraintlayoutVersion = "2.2.1"
lifecycleLivedataKtxVersion = "2.10.0"
lifecycleViewmodelKtxVersion = "2.10.0"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
app-update = { module = "com.google.android.play:app-update", version.ref = "appUpdateVersion" }
biometric = { module = "androidx.biometric:biometric", version.ref = "biometricVersion" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilComposeVersion" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGsonVersion" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferencesVersion" }
gson = { module = "com.google.code.gson:gson", version.ref = "gsonVersion" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltCompilerVersion" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationComposeVersion" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }

core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutinesCore" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }


compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }

logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptorVersion" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieComposeVersion" }
material = { module = "com.google.android.material:material", version.ref = "materialVersion" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtendedVersion" }
paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingCommonAndroidVersion" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocationVersion" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtxVersion" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtxVersion" }
security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCryptoVersion" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timberVersion" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtxVersion" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltWorkVersion" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotationVersion" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayoutVersion" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtxVersion" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtxVersion" }
[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version = "8.12.3" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version = "2.57.2" } # or latest